# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5aecc55655abe7d614e8d565899da86591466a390f130d9057364e278cadea1dc54b67a66351d33df9fa1d4be72896a36e244becf987c9a0f8728262c499674

test:
  secret_key_base: 1695001ac363d63b4f274fcdaa49e2b37b0e19d9849a82c6a51d5f8c32b83b51b54b2f48e6f49ba799f1af82abcf899d8b2ccac3ee65d2fa2c3c513230f2347c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
